name: Just a test CI

on:
  # pull_request_review:
  #   types: [submitted]
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MFEEDDOMAIN: bo.mfeeduno.com
      DOCKERUSER: fortbautista

    steps:
      - uses: actions/checkout@v3

      - name: Change Config
        run: |
          sed -i 's, localhost:44343, $MFEEDDOMAIN, g' src/MFeed/src/environments/environment.ts

      - name: Docker Image build
        run: |
          docker version
          docker build --progress plain -t $DOCKERUSER-${{ github.event.repository.name }}-${{ github.ref_name }}:latest .
          docker tag $DOCKERUSER-${{ git.github.event.repository.name }}-${{ github.ref_name }}:latest $DOCKERUSER-${{ git.github.event.repository.name }}-${{ github.ref_name }}:${{ github.job }}
          docker images

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secret.DOCKER_USERNAME }}
          password: ${{ secret.DOCKER_PW }}